### ISSUE TITLE
Conpare covid-19 to corona-beer stats

### ISSUE THREAD

**Issue by lustricker** [kredde/corona-outbreak#2]
### Description
It would be interesting having a statistic which shows a correlation between the covid-19 spread and the corona beer sales.

Thanks for your effort.

**Comment by kredde** [comment]
@lustricker Thanks for your input!
![giphy](https://user-images.githubusercontent.com/5833086/77461203-7d560200-6e02-11ea-9f57-bc5afa45dfbd.gif)

**Comment by kredde** [comment]
Thanks for your input: this is the curve @lustricker 
![giphy](https://user-images.githubusercontent.com/5833086/77461326-ac6c7380-6e02-11ea-8595-248642488372.gif)
